### PR TITLE
Python 2.6 compat fixes

### PR DESCRIPTION
**Pull request by jmalonzo**

### CODE REVIEW

**Comment by scottpersinger** [comment]
This looks generally OK, but I'd rather have it preserve the old behavior (use writeheader) when available rather than just rewriting.

**Comment by ViViDboarder** [comment]
It looks like this patch is still needed for compatibility with Python 2.6. 

Is Heroku actively developing this? Or just merging changes. The comments provided here seem trivial and could probably be done in short work...

**Comment by jmalonzo** [comment]
I have no time to update the patch atm but feel free to update if anyone is in hurry.

**Comment by scottpersinger** [comment]
Ya, the `iterfind` change is ok, but for the CSV changes I'd rather see the existing functionality maintained for 2.7. For example, I don't know if there are perf implications of the change.

**Comment by ViViDboarder** [comment]
Just posted an updated PR over on #17

**Comment by scottpersinger** [comment]
Fixed in #17

**Pull request closed without merging**
