### PR TITLE
Bump version to 2.1.0

### PR DESCRIPTION
**Pull request by lambacck**

### CODE REVIEW

**Comment by sigmavirus24** [comment]
If this includes the new method, shouldn't it be `2.1.0` to indicate a new feature?

**Comment by lambacck** [comment]
:eyes: I changed it to be 2.1.0 due to the addition of new methods.

**Comment by sigmavirus24** [comment]
👍 :shipit:

**Comment by lambacck** [comment]
Released: https://pypi.python.org/pypi/salesforce-bulk/2.1.0

**Pull request merged**
